### ISSUE TITLE
[Bug] Crash on startup due to corrupted recent files list

### ISSUE THREAD

**Issue by ColinDuquesnoy** [OpenCobolIDE/OpenCobolIDE#115]
This issue was reported by a user in a private mail:

> I installed OpenCobolIDE 4.5.0 about a week ago and have been using is solidly since then. I have been very impressed with it and have enjoyed my usage of it. Even though I currently have a problem with it you can still put me down as a satisfied user.
Earlier today I was doing some sorting out and deleted some files that I has used OpenCobolIDE to view. Later in the day I wanted to do some more work on a utility I am writing for the GnuCOBOL project and found that OpenCobolIDE would not start from my menu. I opened a terminal and tried to start it from there. The following is what it displayed:

```
(/home/robert)$ opencobolide
INFO::open_cobol_ide::version: 4.5.0
Traceback (most recent call last):
  File "/usr/local/bin/opencobolide", line 11, in
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/open_cobol_ide/main.py", line 12, in main
    app = Application()
  File "/usr/local/lib/python3.4/dist-packages/open_cobol_ide/app.py", line 57, in __init__
    self.file = FileController(self)
  File "/usr/local/lib/python3.4/dist-packages/open_cobol_ide/controllers/file.py", line 42, in __init__
    icon_provider=FileIconProvider())
  File "/usr/local/lib/python3.4/dist-packages/pyqode/core/widgets/menu_recents.py", line 160, in __init__
    self.update_actions()
  File "/usr/local/lib/python3.4/dist-packages/pyqode/core/widgets/menu_recents.py", line 168, in update_actions
    for file in self.manager.get_recent_files():
  File "/usr/local/lib/python3.4/dist-packages/pyqode/core/widgets/menu_recents.py", line 80, in get_recent_files
    files = self.get_value('list', [])
  File "/usr/local/lib/python3.4/dist-packages/pyqode/core/widgets/menu_recents.py", line 63, in get_value
    self._settings.value('recent_files/%s' % key, default)])
TypeError: 'NoneType' object is not iterable
(/home/robert)$
```

**Comment by ColinDuquesnoy** [comment]
Fixed in pyqode.core 2.6.2
