### ISSUE TITLE
[Bug] OCIDE does not start if cobc check on startup doesn't work

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#187]
When I've tried to find a workaround for #183 with VCVARS32 set the following message was raised during startup:

```
---------------------------
cx_Freeze: Python error in main script
---------------------------
Traceback (most recent call last):
  File "C:\Dev\OpenCobolIDE\open_cobol_ide\memoize.py", line 39, in __call__
KeyError: (<class 'open_cobol_ide.compilers.GnuCobolCompiler'>, 'D:/dev/my_cobc.bat')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
  File "OpenCobolIDE", line 9, in <module>
  File "C:\Dev\OpenCobolIDE\open_cobol_ide\main.py", line 12, in main
  File "C:\Dev\OpenCobolIDE\open_cobol_ide\app.py", line 78, in __init__
  File "C:\Dev\OpenCobolIDE\open_cobol_ide\compilers.py", line 78, in check_compiler
  File "C:\Dev\OpenCobolIDE\open_cobol_ide\compilers.py", line 232, in is_working
  File "C:\Dev\OpenCobolIDE\open_cobol_ide\memoize.py", line 41, in __call__
  File "C:\Dev\OpenCobolIDE\open_cobol_ide\compilers.py", line 190, in check_compiler
  File "C:\Dev\OpenCobolIDE\open_cobol_ide\compilers.py", line 124, in generate
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Me\\AppData\\Local\\Temp\\cobc_wrapper.bat'

---------------------------
OK   
---------------------------
```

Problems during check if cobc works should not prevent OCIDE to start.

**Comment by ColinDuquesnoy** [comment]
Should be fixed in master branch.
