### ISSUE TITLE
[Bug] Shared libraries for GnuCOBOL are copied to source directory!!!

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#241]
This was likely added for solving some bug but the current behaviour is a bug itself - Nobody wants to pollute (every?) source directory with runtime dlls.

After click to "Compile" the following files were copied to the source directory:

* libcharset-1.dll
* libcob.dll
* libcob-1.dll
* libdb-6.1.dll
* libgcc_s_dw2-1.dll
* libgmp-10.dll
* libgmp-16.dll
* libgmpxx-4.dll
* libgomp-1.dll
* libiconv-2.dll
* libintl-8.dll
* liblto_plugin-0.dll
* libmpfr-4.dll
* libmpir-16.dll
* libquadmath-0.dll
* libssp-0.dll
* libstdc++-6.dll
* mingwm10.dll
* pdcurses.dll
* pthreadGC2.dll
* pthreadGCE2.dll
* zlib1.dll

## System information

- OpenCobolIDE: 4.7.dev37
- GnuCOBOL: GNU Cobol 1.1.0
- Python: 3.4.3 (32bits)
- Qt: 5.5.0
- PyQt: 5.5
- pyqode.core: 2.7.0.dev33
- pyqode.cobol: 2.7.dev0
- pyqode.qt: 2.7.dev0
- pygments: 2.0.2
- QDarkStyle: 2.1

## Log

~~~~~
DEBUG::open_cobol_ide.controllers.view::showing page <Page.HOME: 0>
DEBUG::open_cobol_ide.msvc::querying vcvarsall: "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvarsall.bat" x86 set
DEBUG::open_cobol_ide.compilers::check compiler
DEBUG::open_cobol_ide.compilers::process environment: ['TMP=C:\\Users\\Simon\\AppData\\Local\\Temp', 'ALLUSERSPROFILE=C:\\ProgramData', 'WINDOWS_TRACING_FLAGS=3', 'PROGRAMW6432=C:\\Program Files', 'PROGRAMFILES=C:\\Program Files (x86)', 'PATH=C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VSTSDB\\Deploy;C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\Common7\\IDE\\;C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\BIN;C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\Common7\\Tools;C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319;C:\\Windows\\Microsoft.NET\\Framework\\v3.5;C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\VCPackages;C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v7.0A\\bin\\NETFX 4.0 Tools;C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v7.0A\\bin;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Program Files (x86)\\Microsoft SQL Server\\100\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\100\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\100\\DTS\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\110\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\110\\Tools\\Binn\\;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\TortoiseSVN\\bin;C:\\GnuCOBOL\\bin;C:\\Program Files (x86)\\OpenCobolIDE\\GnuCOBOL\\bin', 'WINDIR=C:\\Windows', 'PSMODULEPATH=C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules\\', 'LOCALAPPDATA=C:\\Users\\Simon\\AppData\\Local', 'COMMONPROGRAMFILES=C:\\Program Files (x86)\\Common Files', 'include=C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\INCLUDE;C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v7.0A\\include', 'COB_LIB_PATH=C:\\Program Files (x86)\\OpenCobolIDE\\GnuCOBOL\\lib', 'COB_SCREEN_ESC=Y', 'TK_LIBRARY=C:\\Program Files (x86)\\OpenCobolIDE_dev\\tk', 'APPDATA=C:\\Users\\Simon\\AppData\\Roaming', 'USERDOMAIN=DOMAIN', 'HOMEPATH=\\Users\\Simon', 'SESSIONNAME=Console', 'PUBLIC=C:\\Users\\Public', 'COB_CONFIG_DIR=C:\\Program Files (x86)\\OpenCobolIDE\\GnuCOBOL\\config', 'LOGONSERVER=\\\\SERVER-LOGIN', 'libpath=C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319;C:\\Windows\\Microsoft.NET\\Framework\\v3.5;C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\LIB', 'NUMBER_OF_PROCESSORS=2', 'FP_NO_HOST_CHECK=NO', 'OS=Windows_NT', 'PROCESSOR_ARCHITECTURE=x86', 'TEMP=C:\\Users\\Simon\\AppData\\Local\\Temp', 'QT_API=pyqt5', 'USERNAME=simon', 'TCL_LIBRARY=C:\\Program Files (x86)\\OpenCobolIDE_dev\\tcl', 'SYSTEMROOT=C:\\Windows', 'VS100COMNTOOLS=C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\Common7\\Tools\\', 'COB_SCREEN_EXCEPTIONS=Y', 'USERDNSDOMAIN=DOMAIN.LOCAL', 'COMSPEC=C:\\Windows\\system32\\cmd.exe', 'PROGRAMFILES(X86)=C:\\Program Files (x86)', 'COMMONPROGRAMW6432=C:\\Program Files\\Common Files', 'USERPROFILE=C:\\Users\\Simon', 'PROGRAMDATA=C:\\ProgramData', 'PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'PROCESSOR_ARCHITEW6432=AMD64', 'PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 23 Stepping 10, GenuineIntel', 'WINDOWS_TRACING_LOGFILE=C:\\BVTBin\\Tests\\installpackage\\csilogfile.log', 'SYSTEMDRIVE=C:', 'PROCESSOR_LEVEL=6', 'lib=C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\VC\\LIB;C:\\Program Files (x86)\\Microsoft SDKs\\Windows\\v7.0A\\lib', 'COMMONPROGRAMFILES(X86)=C:\\Program Files (x86)\\Common Files', 'COMPUTERNAME=COMPUTER', 'PROCESSOR_REVISION=170a', 'HOMEDRIVE=C:']
DEBUG::open_cobol_ide.compilers::command: C:\Program Files (x86)\OpenCobolIDE\GnuCOBOL\bin\cobc.exe -x -o C:\Users\Simon\AppData\Local\Temp\test.exe C:\Users\Simon\AppData\Local\Temp\test.cbl
DEBUG::open_cobol_ide.compilers::process output: '\n'
DEBUG::open_cobol_ide.compilers::process exit code: 0
INFO::open_cobol_ide.compilers::GnuCOBOL compiler check: success
DEBUG::open_cobol_ide.compilers::getting cobc version: C:\Program Files (x86)\OpenCobolIDE\GnuCOBOL\bin\cobc.exe --version
DEBUG::open_cobol_ide.compilers::parsing version line: cobc (GNU Cobol) 1.1.0
Copyright (C) 2001,2002,2003,2004,2005,2006,2007 Keisuke Nishida
Copyright (C) 2006-2012 Roger While
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Built     May 30 2015 23:52:03
Packaged  Jan 20 2014 07:40:53 UTC
C version "4.8.1"

INFO::open_cobol_ide.app::GnuCOBOL version: GNU Cobol 1.1.0
DEBUG::open_cobol_ide.view.editors.cobol::linter enabled: True
DEBUG::pyqode.core.managers.file::mimetype detected: text/x-cobol
DEBUG::pyqode.core.managers.file::file open: \\SERVER\share\test.cob
DEBUG::pyqode.core.widgets.splittable_tab_widget::current tab changed (old=None, new=CobolCodeEdit(path='\\\\SERVER\\share\\test.cob'))
DEBUG::open_cobol_ide.compilers::detecting file type: \\SERVER\share\test.cob - cp1252
DEBUG::open_cobol_ide.compilers::file type: <FileType.MODULE: 1>
DEBUG::open_cobol_ide.compilers::detecting file type: \\SERVER\share\test.cob - cp1252
DEBUG::open_cobol_ide.compilers::file type: <FileType.MODULE: 1>
INFO::open_cobol_ide.controllers.edit::current editor changed: \\SERVER\share\test.cob
DEBUG::pyqode.core.api.syntax_highlighter::rehighlight duration: 0.996000s
DEBUG::open_cobol_ide.view.editors.cobol::linter enabled: True
DEBUG::open_cobol_ide.compilers::detecting file type: \\SERVER\share\test.cob - cp1252
DEBUG::open_cobol_ide.compilers::file type: <FileType.MODULE: 1>
DEBUG::open_cobol_ide.controllers.view::showing page <Page.EDIT: 1>
ERROR::pyqode.backend::something went bad with worker <function get_outline at 0x034B6588>(data={

[COBOL SOURCE CODE REMOVED]

', 'encoding': 'cp1252'})
ERROR::pyqode.backend::Traceback (most recent call last):
ERROR::pyqode.backend::  File "d:\documents\pyqode.core\pyqode\core\backend\server.py", line 136, in _handle
ERROR::pyqode.backend::  File "d:\documents\pyqode.cobol\pyqode\cobol\backend\workers.py", line 73, in get_outline
ERROR::pyqode.backend::  File "d:\documents\pyqode.cobol\pyqode\cobol\api\parsers\names.py", line 309, in defined_names
ERROR::pyqode.backend::  File "d:\documents\pyqode.cobol\pyqode\cobol\api\parsers\names.py", line 170, in parse_section
ERROR::pyqode.backend::AttributeError: 'NoneType' object has no attribute 'add_child'
DEBUG::open_cobol_ide.compilers::dependencies of \\SERVER\share\test.cob: []
INFO::open_cobol_ide.controllers.cobol::running compilation thread: ['\\\\SERVER\\share\\test.cob']
DEBUG::open_cobol_ide.compilers::detecting file type: \\SERVER\share\test.cob - cp1252
DEBUG::open_cobol_ide.compilers::file type: <FileType.MODULE: 1>
INFO::open_cobol_ide.compilers::compiling \\SERVER\share\test.cob
INFO::open_cobol_ide.compilers::command: C:\Program Files (x86)\OpenCobolIDE\GnuCOBOL\bin\cobc.exe -o \\SERVER\share\test.dll -std=default -debug test.cob
DEBUG::open_cobol_ide.compilers::working directory: \\SERVER\share
DEBUG::open_cobol_ide.compilers::system environment: ['ALLUSERSPROFILE=C:\\ProgramData', 'APPDATA=C:\\Users\\Simon\\AppData\\Roaming', 'COB_SCREEN_ESC=Y', 'COB_SCREEN_EXCEPTIONS=Y', 'CommonProgramFiles=C:\\Program Files (x86)\\Common Files', 'CommonProgramFiles(x86)=C:\\Program Files (x86)\\Common Files', 'CommonProgramW6432=C:\\Program Files\\Common Files', 'COMPUTERNAME=COMPUTER', 'ComSpec=C:\\Windows\\system32\\cmd.exe', 'FP_NO_HOST_CHECK=NO', 'HOMEDRIVE=C:', 'HOMEPATH=\\Users\\Simon', 'LOCALAPPDATA=C:\\Users\\Simon\\AppData\\Local', 'LOGONSERVER=\\\\SERVER-LOGIN', 'NUMBER_OF_PROCESSORS=2', 'OS=Windows_NT', 'Path=C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Program Files (x86)\\Microsoft SQL Server\\100\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\100\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\100\\DTS\\Binn\\;C:\\Program Files (x86)\\Microsoft SQL Server\\110\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\110\\Tools\\Binn\\;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\TortoiseSVN\\bin;C:\\GnuCOBOL\\bin', 'PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'PROCESSOR_ARCHITECTURE=x86', 'PROCESSOR_ARCHITEW6432=AMD64', 'PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 23 Stepping 10, GenuineIntel', 'PROCESSOR_LEVEL=6', 'PROCESSOR_REVISION=170a', 'ProgramData=C:\\ProgramData', 'ProgramFiles=C:\\Program Files (x86)', 'ProgramFiles(x86)=C:\\Program Files (x86)', 'ProgramW6432=C:\\Program Files', 'PSModulePath=C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules\\', 'PUBLIC=C:\\Users\\Public', 'SESSIONNAME=Console', 'SystemDrive=C:', 'SystemRoot=C:\\Windows', 'TEMP=C:\\Users\\Simon\\AppData\\Local\\Temp', 'TMP=C:\\Users\\Simon\\AppData\\Local\\Temp', 'USERDNSDOMAIN=DOMAIN.LOCAL', 'USERDOMAIN=DOMAIN', 'USERNAME=simon', 'USERPROFILE=C:\\Users\\Simon', 'VS100COMNTOOLS=C:\\Program Files (x86)\\Microsoft Visual Studio 10.0\\Common7\\Tools\\', 'windir=C:\\Windows', 'windows_tracing_flags=3', 'windows_tracing_logfile=C:\\BVTBin\\Tests\\installpackage\\csilogfile.log', 'TCL_LIBRARY=C:\\Program Files (x86)\\OpenCobolIDE_dev\\tcl', 'TK_LIBRARY=C:\\Program Files (x86)\\OpenCobolIDE_dev\\tk', 'QT_API=pyqt5']
INFO::open_cobol_ide.compilers::compiler process exit code: 1
INFO::open_cobol_ide.compilers::compiler process output: test.cob:1: Error: Invalid indicator ';' at column 7


INFO::open_cobol_ide.compilers::binary file (\\SERVER\share\test.dll) created:  False
DEBUG::open_cobol_ide.compilers::compile results: 1 - [("test.cob:1: Error: Invalid indicator ';' at column 7\n\n", 2, -1, 0, None, None, '\\\\SERVER\\share\\test.cob')]
DEBUG::open_cobol_ide.compilers::getting cobc version: C:\Program Files (x86)\OpenCobolIDE\GnuCOBOL\bin\cobc.exe --version
DEBUG::open_cobol_ide.compilers::parsing version line: cobc (GNU Cobol) 1.1.0
Copyright (C) 2001,2002,2003,2004,2005,2006,2007 Keisuke Nishida
Copyright (C) 2006-2012 Roger While
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Built     May 30 2015 23:52:03
Packaged  Jan 20 2014 07:40:53 UTC
C version "4.8.1"

DEBUG::open_cobol_ide.compilers::getting cobc version: C:\Program Files (x86)\OpenCobolIDE\GnuCOBOL\bin\cobc.exe --version
DEBUG::open_cobol_ide.compilers::parsing version line: cobc (GNU Cobol) 1.1.0
Copyright (C) 2001,2002,2003,2004,2005,2006,2007 Keisuke Nishida
Copyright (C) 2006-2012 Roger While
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Built     May 30 2015 23:52:03
Packaged  Jan 20 2014 07:40:53 UTC
C version "4.8.1"
~~~~~

**Comment by ColinDuquesnoy** [comment]
Well this was actually a user request (se #226 ).

Maybe we can add an option that specify whether to copy the runtime dlls or not.

**Comment by GitMensch** [comment]
OK - but I strongly suggest that the option is turned of by default.

BTW: Depending on how the files where build [not with the official binaries] you may need the ".manifest" files, too.
