### ISSUE TITLE
[Bug] Background task seem to not work after compiler Change

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#284]
### Description

Steps to reproduce:

* open a file with an error (background check get called and shows the error)
* change compiler under preferences, including Check compiler (compiler works)
* the file is not rechecked (even after edit and save the error mark is still the same)
* after reopening the file the background check works fine again

### System information

- Operating System: Windows
- OpenCobolIDE: 4.7.2.dev2
- GnuCOBOL: cobc (GnuCOBOL) 2.0.20151025
- Python: 3.4.3 (64bits)
- Qt: 5.5.1
- PyQt: 5.5.1
- pyqode.core: 2.9.dev
- pyqode.cobol: 2.9.dev
- pyqode.qt: 2.9.dev
- pygments: 2.1
- QDarkStyle: 2.1

### Application log

```
20:03:35:256::WARNING::10740::pyqode.core.api.client::the socket operation timed out.
20:03:35:258::WARNING::10740::pyqode.core.api.client::the socket operation timed out.
20:03:35:258::WARNING::10740::pyqode.core.api.client::the socket operation timed out.
20:03:35:259::WARNING::10740::pyqode.core.api.client::the socket operation timed out.
20:03:35:259::WARNING::10740::pyqode.core.api.client::the socket operation timed out.
20:03:35:929::WARNING::10740::pyqode.core.api.client::the socket operation timed out.
20:03:35:929::WARNING::10740::pyqode.core.api.client::the socket operation timed out.
20:03:36:927::WARNING::10740::pyqode.core.api.client::the socket operation timed out.
20:03:36:927::WARNING::10740::pyqode.core.api.client::the socket operation timed out.
20:03:37:221::INFO::10740::open_cobol_ide.controllers.edit::applying settings
20:03:37:932::WARNING::10740::pyqode.core.api.client::the socket operation timed out.
20:03:38:935::WARNING::10740::pyqode.core.api.client::the socket operation timed out.
20:03:39:935::WARNING::10740::pyqode.core.api.client::the socket operation timed out.
20:03:40:929::WARNING::10740::pyqode.core.api.client::the socket operation timed out.
20:03:41:934::WARNING::10740::pyqode.core.api.client::the socket operation timed out.
20:03:42:934::WARNING::10740::pyqode.core.api.client::the socket operation timed out.
20:03:43:932::WARNING::10740::pyqode.core.api.client::the socket operation timed out.
20:03:44:928::WARNING::10740::pyqode.core.api.client::the socket operation timed out.
20:03:45:930::WARNING::10740::pyqode.core.api.client::the socket operation timed out.
20:03:46:936::WARNING::10740::pyqode.core.api.client::the socket operation timed out.
20:03:47:931::WARNING::10740::pyqode.core.api.client::the socket operation timed out.
20:03:48:936::WARNING::10740::pyqode.core.api.client::the socket operation timed out.
20:03:49:933::WARNING::10740::pyqode.core.api.client::the socket operation timed out.
20:03:50:926::WARNING::10740::pyqode.core.api.client::the socket operation timed out.
20:06:33:464::ERROR::10740::qcrash.backends.github::failed to send bug report on github. response={'code': 401, 'json': {'documentation_url': 'https://developer.github.com/v3', 'message': 'Bad credentials'}}
Traceback (most recent call last):
  File "d:\programme\entwicklung\python\lib\site-packages\open_cobol_ide\extlibs\qcrash\_extlibs\github.py", line 247, in _http
    response = opener.open(request, timeout=TIMEOUT)
  File "d:\programme\entwicklung\python\lib\urllib\request.py", line 469, in open
    response = meth(req, response)
  File "d:\programme\entwicklung\python\lib\urllib\request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "d:\programme\entwicklung\python\lib\urllib\request.py", line 507, in error
    return self._call_chain(*args)
  File "d:\programme\entwicklung\python\lib\urllib\request.py", line 441, in _call_chain
    result = func(*args)
  File "d:\programme\entwicklung\python\lib\urllib\request.py", line 587, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\programme\entwicklung\python\lib\site-packages\open_cobol_ide\extlibs\qcrash\backends\github.py", line 62, in send_report
    ret = repo.issues.post(title=title, body=body)
  File "d:\programme\entwicklung\python\lib\site-packages\open_cobol_ide\extlibs\qcrash\_extlibs\github.py", line 125, in __call__
    return self._gh._http(self._method, self._path, **kw)
  File "d:\programme\entwicklung\python\lib\site-packages\open_cobol_ide\extlibs\qcrash\_extlibs\github.py", line 261, in _http
    raise ApiError(url, req, resp)
qcrash._extlibs.github.ApiError: https://api.github.com/repos/OpenCobolIDE/OpenCobolIDE/issues
```

**Comment by ColinDuquesnoy** [comment]
> 20:03:50:926::WARNING::10740::pyqode.core.api.client::the socket operation timed out.

This one looks fishy. Does it happen every time you do these steps (I've just tried on linux, no problems).

**Comment by ColinDuquesnoy** [comment]
Sorry, I can't reproduce this on my  windows development machine. 

If you can reproduce it, attach the source file with the error and the complete log file.

**Comment by GitMensch** [comment]
I've set the configuration (manually) to use the shipped GC 1.1 MinGW build - but I cannot get OCIDE to show the errors in editor window at all?

* check compiler ->check compilation is fine
* editor->show errors is active
* compilation leads to `TEST3.COB:11: Error: syntax error, unexpected Identifier, expecting EXTERNAL or GLOBAL` which is shown in Issue pane

[TEST3.COB.TXT](https://github.com/OpenCobolIDE/OpenCobolIDE/files/156839/TEST3.COB.TXT)

What did I missed?

**Comment by ColinDuquesnoy** [comment]
Does the code completion work? Looks like communication issue between the backend and the frontend...

**Comment by GitMensch** [comment]
> Does the code completion work? Looks like communication issue between the backend and the frontend...

Both code completion and navigation tree are working.
