### ISSUE TITLE
[Bug] [Unhandled exception] FileNotFoundError

### ISSUE THREAD

**Issue by fatman2021** [OpenCobolIDE/OpenCobolIDE#296]
## Steps to reproduce

PLEASE DESCRIBE THE CONTEXT OF THIS BUG AND THE STEPS TO REPRODUCE!

## Traceback

```
  File "/usr/lib/python3.5/site-packages/open_cobol_ide/controllers/file.py", line 129, in save_current
    self.ui.tabWidgetEditors.save_current()
  File "/usr/lib/python3.5/site-packages/open_cobol_ide/extlibs/pyqode/core/widgets/splittable_tab_widget.py", line 1187, in save_current
    self._save(editor)
  File "/usr/lib/python3.5/site-packages/open_cobol_ide/extlibs/pyqode/core/widgets/splittable_tab_widget.py", line 1197, in _save
    with open(path, encoding=encoding) as f:

FileNotFoundError: [Errno 2] No such file or directory: '/home/main/tmp.cbl'
```

## System information

- Operating System: ManjaroLinux
- OpenCobolIDE: 4.7.1
- GnuCOBOL: cobc (GNU Cobol) 2.0.0
- Python: 3.5.1 (64bits)
- Qt: 5.5.1
- PyQt: 5.5.1
- pyqode.core: 2.8.0
- pyqode.cobol: 2.8.0
- pyqode.qt: 2.8.0
- pygments: 2.1
- QDarkStyle: 2.1

## Application log

```
20:26:46:302::INFO::1603::open_cobol_ide::version: 4.7.1
20:27:07:945::INFO::1603::open_cobol_ide.compilers::GnuCOBOL compiler check: success
20:27:07:945::INFO::1603::open_cobol_ide.compilers::Executable extension: 
20:27:07:945::INFO::1603::open_cobol_ide.compilers::Module extension: .so
20:27:07:954::INFO::1603::open_cobol_ide.app::GnuCOBOL version: cobc (GNU Cobol) 2.0.0
18:14:05:669::CRITICAL::1603::open_cobol_ide.app::unhandled exception:
  File "/usr/lib/python3.5/site-packages/open_cobol_ide/extlibs/pyqode/core/api/client.py", line 336, in _on_ready_read
    self._read_payload()
  File "/usr/lib/python3.5/site-packages/open_cobol_ide/extlibs/pyqode/core/api/client.py", line 322, in _read_payload
    results = obj['results']
KeyError: 'results'
18:14:12:528::ERROR::1603::pyqode.backend::Traceback (most recent call last):
18:14:12:529::ERROR::1603::pyqode.backend::  File "/usr/lib/python3.5/site-packages/open_cobol_ide/backend.py", line 28, in <module>
18:14:12:529::ERROR::1603::pyqode.backend::    backend.serve_forever()
18:14:12:530::ERROR::1603::pyqode.backend::  File "/usr/lib/python3.5/site-packages/open_cobol_ide/extlibs/pyqode/core/backend/server.py", line 215, in serve_forever
18:14:12:530::ERROR::1603::pyqode.backend::    server = JsonServer(args=args)
18:14:12:531::ERROR::1603::pyqode.backend::  File "/usr/lib/python3.5/site-packages/open_cobol_ide/extlibs/pyqode/core/backend/server.py", line 170, in __init__
18:14:12:531::ERROR::1603::pyqode.backend::    self, ('127.0.0.1', int(args.port)), self._Handler)
18:14:12:531::ERROR::1603::pyqode.backend::  File "/usr/lib/python3.5/socketserver.py", line 443, in __init__
18:14:12:531::ERROR::1603::pyqode.backend::    self.server_bind()
18:14:12:532::ERROR::1603::pyqode.backend::  File "/usr/lib/python3.5/socketserver.py", line 457, in server_bind
18:14:12:532::ERROR::1603::pyqode.backend::    self.socket.bind(self.server_address)
18:14:12:533::ERROR::1603::pyqode.backend::OSError: [Errno 98] Address already in use
18:26:22:866::WARNING::1603::pyqode.core.managers.modes::potential memory leak detected on mode <pyqode.core.modes.filewatcher.FileWatcherMode object at 0x7f6968154048>...
Install the objgraph package to know what objects are holding references the mode.
18:29:54:208::WARNING::1603::pyqode.core.managers.modes::potential memory leak detected on mode <pyqode.core.modes.filewatcher.FileWatcherMode object at 0x7f696815b048>...
Install the objgraph package to know what objects are holding references the mode.
18:34:05:171::WARNING::1603::pyqode.core.managers.modes::potential memory leak detected on mode <pyqode.core.modes.filewatcher.FileWatcherMode object at 0x7f696ab78438>...
Install the objgraph package to know what objects are holding references the mode.
21:53:38:359::INFO::1603::open_cobol_ide.controllers.cobol::running compilation thread: ['/home/main/tmp.cbl']
21:53:38:398::INFO::1603::open_cobol_ide.compilers::compiling /home/main/tmp.cbl
21:53:50:093::INFO::1603::open_cobol_ide.compilers::binary file '/home/main/bin/tmp' created:  True
21:53:50:094::INFO::1603::open_cobol_ide.compilers::compile results: 0 - []
21:53:52:839::INFO::1603::open_cobol_ide.controllers.cobol::running compilation thread: ['/home/main/tmp.cbl']
21:53:52:840::INFO::1603::open_cobol_ide.compilers::compiling /home/main/tmp.cbl
21:53:52:841::INFO::1603::open_cobol_ide.compilers::compilation skipped, up to date...
21:53:52:862::INFO::1603::open_cobol_ide.controllers.cobol::running program
21:55:17:786::CRITICAL::1603::open_cobol_ide.app::unhandled exception:
  File "/usr/lib/python3.5/site-packages/open_cobol_ide/controllers/file.py", line 129, in save_current
    self.ui.tabWidgetEditors.save_current()
  File "/usr/lib/python3.5/site-packages/open_cobol_ide/extlibs/pyqode/core/widgets/splittable_tab_widget.py", line 1187, in save_current
    self._save(editor)
  File "/usr/lib/python3.5/site-packages/open_cobol_ide/extlibs/pyqode/core/widgets/splittable_tab_widget.py", line 1197, in _save
    with open(path, encoding=encoding) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/main/tmp.cbl'
21:55:21:667::INFO::1603::open_cobol_ide.view.dialogs.report_bug::System informations:
- Operating System: ManjaroLinux
- OpenCobolIDE: 4.7.1
- GnuCOBOL: cobc (GNU Cobol) 2.0.0
- Python: 3.5.1 (64bits)
- Qt: 5.5.1
- PyQt: 5.5.1
- pyqode.core: 2.8.0
- pyqode.cobol: 2.8.0
- pyqode.qt: 2.8.0
- pygments: 2.1
- QDarkStyle: 2.1
21:55:46:289::ERROR::1603::open_cobol_ide.view.dialogs.report_bug::failed to send bug report
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/open_cobol_ide/extlibs/github.py", line 166, in _http
    response = opener.open(request, timeout=TIMEOUT)
  File "/usr/lib/python3.5/urllib/request.py", line 471, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 509, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 589, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/open_cobol_ide/view/dialogs/report_bug.py", line 85, in submit
    ret = repo.issues.post(title=data['title'], body=data['body'])
  File "/usr/lib/python3.5/site-packages/open_cobol_ide/extlibs/github.py", line 203, in __call__
    return self._gh._http(self._method, self._path, **kw)
  File "/usr/lib/python3.5/site-packages/open_cobol_ide/extlibs/github.py", line 178, in _http
    raise ApiError(url, req, resp)
github.ApiError: https://api.github.com/repos/OpenCobolIDE/OpenCobolIDE/issues
```

**Comment by ColinDuquesnoy** [comment]
Thank you for reporting.

**Comment by ColinDuquesnoy** [comment]
Should be fixed in latest commit on master branch.
