### ISSUE TITLE
pyqode.core.widgets.splittable_tab_widget::exception while opening file

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#312]
### Description

~~~~
10:36:07:476::ERROR::6540::pyqode.core.widgets.splittable_tab_widget::exception while opening file
Traceback (most recent call last):
  File "d:\documents\pyqode.core\pyqode\core\widgets\splittable_tab_widget.py", line 1369, in open_document
  File "d:\documents\pyqode.core\pyqode\core\managers\file.py", line 275, in open
  File "d:\documents\pyqode.core\pyqode\core\widgets\code_edits.py", line 152, in setPlainText
  File "d:\documents\pyqode.core\pyqode\core\modes\pygments_sh.py", line 218, in set_lexer_from_filename
  File "C:\Python34\lib\site-packages\pygments\lexers\__init__.py", line 147, in get_lexer_for_filename
  File "C:\Python34\lib\site-packages\pygments\lexers\__init__.py", line 110, in find_lexer_class_for_filename
  File "C:\Python34\lib\site-packages\pygments\lexers\__init__.py", line 41, in _load_lexers
  File "c:\python\32-bit\3.4\lib\importlib\_bootstrap.py", line 2237, in _find_and_load
  File "c:\python\32-bit\3.4\lib\importlib\_bootstrap.py", line 2224, in _find_and_load_unlocked
ImportError: No module named 'pygments.lexers.foxpro'
~~~~

Happened on opening a file with extension ".PRG"

~~~~
---------------------------
Failed to open path
---------------------------
Failed to open path: No module named 'pygments.lexers.foxpro'
---------------------------
OK   
---------------------------
~~~~

### System information

- Operating System: Windows
- OpenCobolIDE: 4.7.3.dev24
- GnuCOBOL: 
- Python: 3.4.3 (32bits)
- Qt: 5.5.1
- PyQt: 5.5.1
- pyqode.core: 2.9.dev
- pyqode.cobol: 2.9.dev
- pyqode.qt: 2.9.dev
- pygments: 2.0.2
- QDarkStyle: 2.1

Application log: https://gist.github.com/1c14bcffa976ea3909fdfb5a5fad74d6

**Comment by GitMensch** [comment]
Temporary workaround: add the file extension to "associated extensions" and disable background check for the file after opening it.

**Comment by ColinDuquesnoy** [comment]
I fixed the unhandled ImportError in pyqode. If such an issue happen it will fallback to plain text. I also improved my freeze script to include all pygments lexers, which means you will now have syntax highlighting in your .PRG file (and potentially other file types too).
