### ISSUE TITLE
[Unhandled exception] AttributeError

### ISSUE THREAD

**Issue by colliplanura** [OpenCobolIDE/OpenCobolIDE#379]
### Description

Falha na criação de programa a partir de template.
Problema na abertura da janela de edição (caixa menor que o espaço disponível).

### Traceback

```
  File "/usr/lib/python3/dist-packages/open_cobol_ide/controllers/file.py", line 146, in save_as
    self.recent_files_manager.open_file(fn)
  File "/usr/lib/python3/dist-packages/open_cobol_ide/extlibs/pyqode/core/widgets/menu_recents.py", line 118, in open_file
    self.set_value('list', files)
  File "/usr/lib/python3/dist-packages/open_cobol_ide/extlibs/pyqode/core/widgets/menu_recents.py", line 82, in set_value
    value = [os.path.normpath(pth) for pth in value]
  File "/usr/lib/python3/dist-packages/open_cobol_ide/extlibs/pyqode/core/widgets/menu_recents.py", line 82, in <listcomp>
    value = [os.path.normpath(pth) for pth in value]
  File "/usr/lib/python3.5/posixpath.py", line 333, in normpath
    initial_slashes = path.startswith(sep)

AttributeError: 'NoneType' object has no attribute 'startswith'
```

### System information

- Operating System: Ubuntu
- OpenCobolIDE: 4.7.4
- GnuCOBOL: cobc (OpenCOBOL) 1.1.0
- Python: 3.5.2+ (64bits)
- Qt: 5.6.1
- PyQt: 5.7
- pyqode.core: 2.10.1
- pyqode.cobol: 2.10.1
- pyqode.qt: 2.10.0
- pygments: 2.1.3
- QDarkStyle: 2.2

Application log: https://gist.github.com/1a95db6156d6aa05aa635c28880d5c19

**Comment by GitMensch** [comment]
In English:

> Failed to create program from template.
> Problem in opening the edit window (box smaller than available space).

**Comment by ColinDuquesnoy** [comment]
I see that you're running OCIDE 4.7.4 with PyQt 5.7, those two version are incompatible. Please try with ocide 4.7.5. 

- first uninstall the debian package if you've use one
- then install OCIDE from PyPi: ``sudo pip3 install OpenCobolIDE --upgrade``

**Comment by datamaskinen** [comment]
I did as you told .... but now i get this:

opencobolide 
Traceback (most recent call last):
  File "/usr/local/bin/opencobolide", line 11, in <module>
    load_entry_point('OpenCobolIDE==4.7.5', 'gui_scripts', 'opencobolide')()
  File "/usr/local/lib/python2.7/dist-packages/open_cobol_ide/main.py", line 29, in main
    from pyqode.qt import QtGui
  File "/usr/local/lib/python2.7/dist-packages/pyqode/qt/__init__.py", line 156, in <module>
    autodetect()
  File "/usr/local/lib/python2.7/dist-packages/pyqode/qt/__init__.py", line 126, in autodetect
    raise PythonQtError('No Qt bindings could be found')
pyqode.qt.PythonQtError: No Qt bindings could be found

**Comment by datamaskinen** [comment]
aha .... sorry for last post .... i used pip istead of pip3

Now it is working .... thank you
