### ISSUE TITLE
problem "failed to find a working GnuCOBOL compiler" when multiple files are opened

### ISSUE THREAD

**Issue by GitMensch** [OpenCobolIDE/OpenCobolIDE#414]
https://gist.github.com/anonymous/0b5f988db5a5ce6b9d4537c5ab9d7772

test case:

* open multiple files from explorer (multi-select + ENTER)
* OCIDE is opened multiple times
* each OCIDE instance runs the compiler check
* race condition: one of the instances deletes test file and/or cannot create the temporary test module
* all but one OCIDE instances have

```
17:32:44:981::INFO::1796::open_cobol_ide.compilers::GnuCOBOL compiler check: fail (0/1)
17:32:44:981::INFO::1796::open_cobol_ide.compilers::Module extension: .dll
17:32:44:981::ERROR::1796::open_cobol_ide.compilers::failed to remove test file: 'C:\\Users\\simon\\AppData\\Local\\Temp\\test.dll'
Traceback (most recent call last):
  File "open_cobol_ide\memoize.py", line 39, in __call__
KeyError: (<class 'open_cobol_ide.compilers.GnuCobolCompiler'>, 'cobc.exe')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "open_cobol_ide\compilers.py", line 335, in check_compiler
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden: 'C:\\Users\\simon\\AppData\\Local\\Temp\\test.cbl'
```

in their log and show

```
---------------------------
COBOL compiler not found or not working
---------------------------
Failed to find a working GnuCOBOL compiler!
The IDE will continue to work but you won't be able to compile...

Tip: Ensure that there is no additional installation of MinGW in C:\MinGW
---------------------------
OK   
---------------------------
```

Things to watch out:

* don't let the complete compiler check fail if the test module "vanished" after the test is run (fine tuning this may be difficult as we want to fail if the test module cannot be created by cobc or run via cobcrun)
* try to synchronize multiple instances, allowing only one (this may be a preference setting)
* if allowing multiple instances make sure the test is not run in parallel

**Comment by ColinDuquesnoy** [comment]
I am not going to make such big changes, I think using a guid as the temporary filename would be good enough.
