### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\u02d8' 

### ISSUE THREAD

**Issue by Martinfx** [OpenCobolIDE/OpenCobolIDE#425]
Hello i have problem with save file with source code.

```
17:54:55:709::ERROR::7880::pyqode.backend::something went bad with worker <function lint at 0x05385BB8>(data={'max_line_length': 79, 'encoding': 'cp1252', 'code': '    

17:54:55:712::ERROR::7880::pyqode.backend::Traceback (most recent call last):
17:54:55:712::ERROR::7880::pyqode.backend::  File "d:\users\colin\documents\pyqode.core\pyqode\core\backend\server.py", line 136, in _handle
17:54:55:712::ERROR::7880::pyqode.backend::  File "open_cobol_ide\linter.py", line 75, in lint
17:54:55:712::ERROR::7880::pyqode.backend::  File "c:\python\32-bit\3.4\lib\encodings\cp1252.py", line 19, in encode
17:54:55:713::ERROR::7880::pyqode.backend::UnicodeEncodeError: 'charmap' codec can't encode character '\u02d8' in position 28703: character maps to <undefined>

```

- Operating System: Windows 7
- OpenCobolIDE: 4.7.6
- GnuCOBOL: cobc (GnuCOBOL) 2.0.0
- Qt: 5.5.1
- PyQt: 5.5.1
- pyqode.core: 2.11.0
- pyqode.cobol: 2.11.0
- pyqode.qt: 2.10.0
- pygments: 2.1.3
- QDarkStyle: 2.3.0

**Comment by ColinDuquesnoy** [comment]
I'll need more information:

- ideally I'd need the offending source file (If it is proprietary code try to submit a sample file that reproduce the problem)
- the verbose logs would be helpful (About -> Log -> Choose PYQODE_DEBUG level, restart the IDE and reproduce the issue). See the documentation to know where to retrieve log files: https://opencobolide.readthedocs.io/en/latest/faq.html#where-can-i-find-ocide-s-log-file

**Comment by Martinfx** [comment]
This is verbose log with error, this bug is broken polish characters.
Coding page in editor was 1252 windows (Western)
[OpenCobolIDE-11864.txt](https://github.com/OpenCobolIDE/OpenCobolIDE/files/1084960/OpenCobolIDE-11864.txt)

**Comment by ColinDuquesnoy** [comment]
Thank you. I'll investigate this issue when I'll have some free time for OCIDE (which might take a while).
